// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0gm-LuE1-Xzq7IgcnJd90ntLQ3gMCQ3o',
    appId: '1:854545757786:web:2e85c91bc3971fd3e38a63',
    messagingSenderId: '854545757786',
    projectId: 'cashew-but-better',
    authDomain: 'cashew-but-better.firebaseapp.com',
    storageBucket: 'cashew-but-better.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd3oY5-cIo0dRvpqFYfil3rKYAJTjsUc8',
    appId: '1:854545757786:android:24c0baf05cda4264e38a63',
    messagingSenderId: '854545757786',
    projectId: 'cashew-but-better',
    storageBucket: 'cashew-but-better.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_IVwhQb3tPQytxJTeJEMWSXUVFYKvL0',
    appId: '1:854545757786:ios:8c5c02758ab3c346e38a63',
    messagingSenderId: '854545757786',
    projectId: 'cashew-but-better',
    storageBucket: 'cashew-but-better.firebasestorage.app',
    androidClientId: '854545757786-3bp0dgf7pv5pjucfm1vj6t4508pspdos.apps.googleusercontent.com',
    iosClientId: '854545757786-eskso332hjn5fh0sui5oa1rhbc3tf7nn.apps.googleusercontent.com',
    iosBundleId: 'com.budget.budget.RunnerTests',
  );

}